/*
    Listar o nome completo (primeiro nome + último nome), 
    a idade e a cidade de todos os passageiros do sexo feminino (sex='w') 
    com mais de 40 anos, residentes no país 'BRAZIL'.
*/

-- Opcao com indexes nao clusterizados
    
ALTER TABLE AIR_PASSENGERS_DETAILS
DROP PRIMARY KEY;

ALTER TABLE AIR_PASSENGERS_DETAILS
DROP constraint fk_passenger_id;

ALTER TABLE AIR_PASSENGERS
DROP PRIMARY KEY;

DROP INDEX sex_idx;
DROP INDEX country_idx;
DROP INDEX bday_idx;

ALTER TABLE AIR_PASSENGERS
ADD PRIMARY KEY(PASSENGER_ID);

ALTER TABLE AIR_PASSENGERS_DETAILS
ADD PRIMARY KEY(PASSENGER_ID);

ALTER TABLE AIR_PASSENGERS_DETAILS
ADD CONSTRAINT fk_passenger_id
FOREIGN KEY (PASSENGER_ID)
REFERENCES AIR_PASSENGERS(PASSENGER_ID);

CREATE INDEX sex_idx ON AIR_PASSENGERS_DETAILS(sex);
CREATE INDEX country_idx ON AIR_PASSENGERS_DETAILS(country);
CREATE INDEX bday_idx ON AIR_PASSENGERS_DETAILS(birthdate);

EXPLAIN PLAN FOR
SELECT
    ap.FIRSTNAME || ' ' || ap.LASTNAME  as FULLNAME,
    apd.BIRTHDATE,
    apd.CITY
FROM
    AIR_PASSENGERS ap
    JOIN AIR_PASSENGERS_DETAILS apd ON ap.PASSENGER_ID = apd.PASSENGER_ID
WHERE
    SEX = 'w'
    AND 
    birthdate <= ADD_MONTHS(SYSDATE,-41*12)
    AND
    COUNTRY = 'BRAZIL';
    
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY());

-- Opcao com index clusterizado

ALTER TABLE AIR_PASSENGERS_DETAILS
DROP PRIMARY KEY;

ALTER TABLE AIR_PASSENGERS_DETAILS
DROP constraint fk_passenger_id;

ALTER TABLE AIR_PASSENGERS
DROP PRIMARY KEY;

ALTER TABLE AIR_PASSENGERS
ADD PRIMARY KEY(PASSENGER_ID);

ALTER TABLE AIR_PASSENGERS_DETAILS
ADD PRIMARY KEY(PASSENGER_ID);

ALTER TABLE AIR_PASSENGERS_DETAILS
ADD CONSTRAINT fk_passenger_id
FOREIGN KEY (PASSENGER_ID)
REFERENCES AIR_PASSENGERS(PASSENGER_ID);

DROP CLUSTER air_passengers_country including tables CASCADE CONSTRAINTS;

CREATE CLUSTER air_passengers_country (
 country varchar(50)
)
INDEX;

CREATE INDEX idx_cl_air_passengers_country ON CLUSTER air_passengers_country;

CREATE CLUSTER air_passengers_country (
 country varchar(50)
)
SIZE 8K
hashkeys 128;

CREATE TABLE AIR_PASSENGERS_DETAILS_CL (
    PASSENGER_ID NUMERIC(12) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    SEX CHAR(1) NOT NULL,
    STREET VARCHAR(100) NOT NULL ,
    CITY VARCHAR(100) NOT NULL,
    ZIP NUMBER(5) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL ,
    EMAILADDRESS VARCHAR(120),
    TELEPHONENO VARCHAR(30)
) CLUSTER air_passengers_country(country);

DELETE FROM AIR_PASSENGERS_DETAILS WHERE STREET IS NULL;

INSERT INTO AIR_PASSENGERS_DETAILS_CL select * from AIR_PASSENGERS_DETAILS;

ALTER TABLE AIR_PASSENGERS_DETAILS_CL
ADD PRIMARY KEY(PASSENGER_ID);

ALTER TABLE AIR_PASSENGERS_DETAILS_CL
ADD CONSTRAINT fk_passenger__id
FOREIGN KEY (PASSENGER_ID)
REFERENCES AIR_PASSENGERS(PASSENGER_ID);

EXPLAIN PLAN FOR
SELECT
    ap.FIRSTNAME || ' ' || ap.LASTNAME  as FULLNAME,
    apd.BIRTHDATE,
    apd.CITY
FROM
    AIR_PASSENGERS ap
    JOIN AIR_PASSENGERS_DETAILS_CL apd ON ap.PASSENGER_ID = apd.PASSENGER_ID
WHERE
    SEX = 'w'
    AND 
    birthdate <= ADD_MONTHS(SYSDATE,-41*12)
    AND
    COUNTRY = 'BRAZIL';
    
SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY());
