DROP TABLE CB102596.AIR_AIRLINES CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_AIRPLANES CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_AIRPORTS CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_AIRPORTS_GEO CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_BOOKINGS CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_FLIGHTS CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_FLIGHTS_SCHEDULES CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_PASSENGERS CASCADE CONSTRAINTS PURGE;
DROP TABLE CB102596.AIR_PASSENGERS_DETAILS CASCADE CONSTRAINTS PURGE;

describe table;

SELECT
  'create table ' || table_name || ' as select * from ARRUDA.' || table_name || ';'
FROM
  all_tables
WHERE
    owner = 'DSILVA'
    AND table_name LIKE 'AIR_%';

SELECT
    segment_name,
    SUM(bytes)/1024 KB
FROM
    user_segments
WHERE
    segment_type='TABLE'
    AND segment_name LIKE 'AIR_%'
GROUP BY
    segment_name
ORDER BY
    2 DESC;
